package api

import (
	"encoding/json"
	"net/http"
	"strings"

	"github.com/go-chi/chi/v5"

	"github.com/mrcook1e/amneziawg-panel/internal/awg"
)

func (h *Handlers) profilesList(w http.ResponseWriter, r *http.Request) {
	writeJSON(w, 200, h.Mgr.ListProfiles())
}

func (h *Handlers) profileGet(w http.ResponseWriter, r *http.Request) {
	v, err := h.Mgr.ProfileInfo(chi.URLParam(r, "id"))
	if err != nil {
		writeErr(w, err)
		return
	}
	writeJSON(w, 200, v)
}

// profileCreateBody is the BYOC ("bring your own config") shape: the admin
// pastes an [Interface] snippet (typically generated by AmneziaWG-Architect),
// the server parses it and binds the obfuscation params to a new profile.
type profileCreateBody struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Snippet     string `json:"snippet"`
}

func (h *Handlers) profileCreate(w http.ResponseWriter, r *http.Request) {
	var in profileCreateBody
	if err := json.NewDecoder(r.Body).Decode(&in); err != nil {
		writeJSON(w, 400, map[string]string{"error": "invalid JSON body"})
		return
	}
	if strings.TrimSpace(in.Snippet) == "" {
		writeJSON(w, 400, map[string]string{"error": "snippet is required"})
		return
	}
	spec, err := awg.ParseObfuscation(in.Snippet)
	if err != nil {
		writeJSON(w, 400, map[string]string{"error": "snippet: " + err.Error()})
		return
	}
	v, err := h.Mgr.CreateProfile(awg.ProfileSpec{
		ID: in.ID, Name: in.Name, Description: in.Description,
		Obf: spec,
	})
	if err != nil {
		writeErr(w, err)
		return
	}
	writeJSON(w, 200, v)
}

// profilePatchBody — Snippet, when present, fully replaces the obfuscation
// block. Name/Description are independent and any subset can be sent.
type profilePatchBody struct {
	Name        *string `json:"name"`
	Description *string `json:"description"`
	Snippet     *string `json:"snippet"`
}

func (h *Handlers) profilePatch(w http.ResponseWriter, r *http.Request) {
	var in profilePatchBody
	if err := json.NewDecoder(r.Body).Decode(&in); err != nil {
		writeJSON(w, 400, map[string]string{"error": "invalid JSON body"})
		return
	}
	patch := awg.ProfilePatch{Name: in.Name, Description: in.Description}
	if in.Snippet != nil {
		if strings.TrimSpace(*in.Snippet) == "" {
			writeJSON(w, 400, map[string]string{"error": "snippet cannot be empty"})
			return
		}
		spec, err := awg.ParseObfuscation(*in.Snippet)
		if err != nil {
			writeJSON(w, 400, map[string]string{"error": "snippet: " + err.Error()})
			return
		}
		patch.Obf = &spec
	}
	v, err := h.Mgr.PatchProfile(chi.URLParam(r, "id"), patch)
	if err != nil {
		writeErr(w, err)
		return
	}
	writeJSON(w, 200, v)
}

func (h *Handlers) profileDelete(w http.ResponseWriter, r *http.Request) {
	if err := h.Mgr.DeleteProfile(chi.URLParam(r, "id")); err != nil {
		writeErr(w, err)
		return
	}
	writeJSON(w, 200, map[string]bool{"success": true})
}

func (h *Handlers) profileRestart(w http.ResponseWriter, r *http.Request) {
	if err := h.Mgr.RestartInterface(chi.URLParam(r, "id")); err != nil {
		writeErr(w, err)
		return
	}
	writeJSON(w, 200, map[string]bool{"success": true})
}
